
OBJECTS = $(SOURCES_DIR)/parser.o \
		$(SOURCES_DIR)/search_word_protocol.o \
 		$(SOURCES_DIR)/crawl.o \
		$(SOURCES_DIR)/dfs_crawl.o \
		$(SOURCES_DIR)/page.o \
		$(SOURCES_DIR)/searcher.o \
		$(SOURCES_DIR)/configuration.o \
		$(SOURCES_DIR)/qury_cache.o \
		$(SOURCES_DIR)/uiSearch.o \
		$(SOURCES_DIR)/coach_searcher.o \

-include ../makefile.common

